// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RTHomePropertyManagement.Models;

#nullable disable

namespace RTHomePropertyManagement.Migrations.RealEstateDb
{
    [DbContext(typeof(RealEstateDbContext))]
    [Migration("20260512210515_AddPropertyFeatureFields")]
    partial class AddPropertyFeatureFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RTHomePropertyManagement.Models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("designation");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("ProfileLink")
                        .HasColumnType("text")
                        .HasColumnName("profile_link");

                    b.HasKey("Id");

                    b.ToTable("agents", "core");
                });

            modelBuilder.Entity("RTHomePropertyManagement.Models.ListingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.HasKey("Id");

                    b.ToTable("listing_types", "core");
                });

            modelBuilder.Entity("RTHomePropertyManagement.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.HasKey("Id");

                    b.ToTable("locations", "core");
                });

            modelBuilder.Entity("RTHomePropertyManagement.Models.PriceRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_label");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("max_price");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("min_price");

                    b.HasKey("Id");

                    b.ToTable("price_ranges", "core");
                });

            modelBuilder.Entity("RTHomePropertyManagement.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int?>("AgentId")
                        .HasColumnType("integer")
                        .HasColumnName("agent_id");

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("integer")
                        .HasColumnName("bathrooms");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("integer")
                        .HasColumnName("bedrooms");

                    b.Property<string>("CeilingHeight")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ceiling_height");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisabledAccess")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("disabled_access");

                    b.Property<string>("Floor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("floor");

                    b.Property<string>("Furnishing")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("furnishing");

                    b.Property<int?>("Garage")
                        .HasColumnType("integer")
                        .HasColumnName("garage");

                    b.Property<string>("GardenSize")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("garden_size");

                    b.Property<bool?>("HasAirCondition")
                        .HasColumnType("boolean")
                        .HasColumnName("has_air_condition");

                    b.Property<bool?>("HasCableTv")
                        .HasColumnType("boolean")
                        .HasColumnName("has_cable_tv");

                    b.Property<bool?>("HasElevator")
                        .HasColumnType("boolean")
                        .HasColumnName("has_elevator");

                    b.Property<bool?>("HasFence")
                        .HasColumnType("boolean")
                        .HasColumnName("has_fence");

                    b.Property<bool?>("HasFireplace")
                        .HasColumnType("boolean")
                        .HasColumnName("has_fireplace");

                    b.Property<bool?>("HasIntercom")
                        .HasColumnType("boolean")
                        .HasColumnName("has_intercom");

                    b.Property<bool?>("HasSwimmingPool")
                        .HasColumnType("boolean")
                        .HasColumnName("has_swimming_pool");

                    b.Property<bool?>("HasVentilation")
                        .HasColumnType("boolean")
                        .HasColumnName("has_ventilation");

                    b.Property<bool?>("HasWifi")
                        .HasColumnType("boolean")
                        .HasColumnName("has_wifi");

                    b.Property<string>("Heating")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("heating");

                    b.Property<bool>("IsForRent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_for_rent");

                    b.Property<bool?>("IsPetFriendly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pet_friendly");

                    b.Property<int?>("ListingTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("listing_type_id");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<int?>("ParkingSpots")
                        .HasColumnType("integer")
                        .HasColumnName("parking_spots");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<string>("PricePeriod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("price_period");

                    b.Property<int?>("PriceRangeId")
                        .HasColumnType("integer")
                        .HasColumnName("price_range_id");

                    b.Property<string>("Renovation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("renovation");

                    b.Property<string>("Security")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("security");

                    b.Property<int?>("SquareFeet")
                        .HasColumnType("integer")
                        .HasColumnName("square_feet");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("WindowType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("window_type");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("integer")
                        .HasColumnName("year_built");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ListingTypeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PriceRangeId");

                    b.ToTable("properties", "core");
                });

            modelBuilder.Entity("RTHomePropertyManagement.Models.PropertyImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("property_images", "core");
                });

            modelBuilder.Entity("RTHomePropertyManagement.Models.Property", b =>
                {
                    b.HasOne("RTHomePropertyManagement.Models.Agent", "Agent")
                        .WithMany("Properties")
                        .HasForeignKey("AgentId");

                    b.HasOne("RTHomePropertyManagement.Models.ListingType", "ListingType")
                        .WithMany("Properties")
                        .HasForeignKey("ListingTypeId");

                    b.HasOne("RTHomePropertyManagement.Models.Location", "Location")
                        .WithMany("Properties")
                        .HasForeignKey("LocationId");

                    b.HasOne("RTHomePropertyManagement.Models.PriceRange", "PriceRange")
                        .WithMany("Properties")
                        .HasForeignKey("PriceRangeId");

                    b.Navigation("Agent");

                    b.Navigation("ListingType");

                    b.Navigation("Location");

                    b.Navigation("PriceRange");
                });

            modelBuilder.Entity("RTHomePropertyManagement.Models.PropertyImage", b =>
                {
                    b.HasOne("RTHomePropertyManagement.Models.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RTHomePropertyManagement.Models.Agent", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RTHomePropertyManagement.Models.ListingType", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RTHomePropertyManagement.Models.Location", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RTHomePropertyManagement.Models.PriceRange", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RTHomePropertyManagement.Models.Property", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
